sudo: false
language: python
python:
  - 3.9
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - pytest
  - pip install coverage
  
