language: python
python:
  - 3.9
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - pytest
  - pip install pytest-cov
  - pytest --cov=./


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "indexhelloworld"
    env: "Indexhelloworld-env"
    bucket_name: "cps847hello"
    bucket_path: "Docker-Container"
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    on:
        branch: "main"
