language: python
python:
  - 3.9
before_install:
      - choco install python3
      - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      - python -m pip install --upgrade pip wheel
script:
  - pytest
