language: python
python:
  - 3.9
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - pytest
  - pip install pytest-cov
  - pytest --cov=./

services:
    - docker
    
before_install:
    - docker build -t KyleCM2/CPS847-ASSIGN2 .

script:
    - docker run KyleCM2/CPS847-ASSIGN2 test --allow-env tests/version.test.ts

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Docker-Container"
    env: "Dockercontainer-env"
    bucket_name: "elasticbeanstalk-us-east-2-222303356119"
    bucket_path: "2021095ryx-index.html"
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    on:
        branch: "main"
