sudo: false
language: python
python:
  - 3.9
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - pytest
  - pip install pytest-cov
  - pytest --cov=./

  
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=0yfvJIkgbXRFmgx+JCgKOuHj5hPAA2ihSGD1s7Go"
  secret_access_key:
    secure: "Encypted <secret-access-key>=0yfvJIkgbXRFmgx+JCgKOuHj5hPAA2ihSGD1s7Go"
  region: "us-east-2"
  app: "Index"
  env: "testing"
  bucket_name: "helloworldindex"
